"""
EMA Crossover Strategy
======================

Description:
    A trend-following strategy that uses Exponential Moving Average (EMA) crossovers
    to generate trading signals. The strategy buys when the fast EMA crosses above
    the slow EMA (bullish crossover) and sells when the fast EMA crosses below the
    slow EMA (bearish crossover).

Entry Conditions:
    - 9-day EMA crosses above 21-day EMA (golden cross)
    - Use 100% of available cash for position sizing

Exit Conditions:
    - 9-day EMA crosses below 21-day EMA (death cross)
    - Sell all shares immediately

Position Sizing:
    Use 100% of available cash on entry signals

Risk Management:
    Exit only on opposite crossover signal (no stop-loss or take-profit)

Timeframe:
    Daily (1D) - checks once per day

Author: Generated by Lumibot Claude Code Agent
Date: 2025-10-29
"""

from lumibot.strategies import Strategy
from lumibot.entities import Asset
from datetime import datetime, timedelta
import pandas as pd
import pandas_ta as ta


class EMACrossoverStrategy(Strategy):
    """
    EMA Crossover Strategy using 9-day and 21-day EMAs.

    This strategy implements a classic trend-following approach where:
    - BUY signal: Fast EMA (9) crosses above Slow EMA (21)
    - SELL signal: Fast EMA (9) crosses below Slow EMA (21)

    The strategy uses 100% of available cash for each trade and holds
    positions until the opposite crossover signal occurs.
    """

    # Default parameters - can be overridden during instantiation
    parameters = {
        "symbol": "SPY",
        "timeframe": "1D",
        "fast_ema_period": 9,
        "slow_ema_period": 21,
        "cash_allocation": 1.0,  # 100% of cash
    }

    def initialize(self):
        """
        Initialize the strategy.

        Sets up:
        - Trading frequency (sleeptime)
        - Strategy parameters
        - State variables for crossover detection
        - Risk management settings
        """
        # Set trading frequency - daily checks
        self.sleeptime = self.parameters.get("timeframe", "1D")

        # Get symbol
        self.symbol = self.parameters.get("symbol", "SPY")

        # EMA periods
        self.fast_ema_period = self.parameters.get("fast_ema_period", 9)
        self.slow_ema_period = self.parameters.get("slow_ema_period", 21)
        self.cash_allocation = self.parameters.get("cash_allocation", 1.0)

        # State variables for crossover detection
        self.previous_fast_ema = None
        self.previous_slow_ema = None
        self.last_crossover_type = None  # 'bullish', 'bearish', or None

        # Position tracking
        self.entry_price = None
        self.entry_time = None
        self.position_type = None  # 'long' or None

        # Calculate minimum bars needed (slow EMA + buffer)
        self.min_bars_needed = self.slow_ema_period * 3

        # Log initialization
        self.log_message(
            f"Initialized {self.__class__.__name__} for {self.symbol} | "
            f"Fast EMA: {self.fast_ema_period}, Slow EMA: {self.slow_ema_period} | "
            f"Timeframe: {self.sleeptime}"
        )

    def on_trading_iteration(self):
        """
        Main trading logic executed at each iteration.

        Flow:
        1. Acquire historical price data
        2. Validate data availability
        3. Calculate 9-day and 21-day EMAs
        4. Detect crossover events
        5. Check current position status
        6. Execute entry logic if crossover detected and not in position
        7. Execute exit logic if opposite crossover detected and in position
        8. Log actions and state
        """
        try:
            # Execute main logic with error handling
            self._execute_trading_logic()

        except Exception as e:
            # Log error but don't crash the strategy
            self.log_message(f"ERROR in trading iteration: {str(e)}")
            import traceback
            self.log_message(traceback.format_exc())

    def _execute_trading_logic(self):
        """
        Core trading logic (wrapped for error handling).
        """
        # 1. Data Acquisition
        current_price = self.get_last_price(self.symbol)

        if current_price is None or current_price <= 0:
            self.log_message("Invalid price data, skipping iteration")
            return

        # Get historical data for EMA calculations
        # Need enough data for slow EMA calculation
        bars = self.get_historical_prices(
            self.symbol,
            length=self.min_bars_needed,
            timestep=self.sleeptime
        )

        # 2. Data Validation
        if bars is None or bars.df.empty:
            self.log_message("No historical data available, skipping iteration")
            return

        df = bars.df

        # Ensure we have enough data
        if len(df) < self.slow_ema_period:
            self.log_message(
                f"Insufficient data: {len(df)} bars, need at least {self.slow_ema_period}"
            )
            return

        # 3. Calculate Technical Indicators - EMAs using pandas_ta
        df['ema_fast'] = ta.ema(df['close'], length=self.fast_ema_period)
        df['ema_slow'] = ta.ema(df['close'], length=self.slow_ema_period)

        # Get current EMA values
        current_fast_ema = df['ema_fast'].iloc[-1]
        current_slow_ema = df['ema_slow'].iloc[-1]

        # Get previous EMA values (from one bar ago)
        if len(df) >= 2:
            previous_fast_ema = df['ema_fast'].iloc[-2]
            previous_slow_ema = df['ema_slow'].iloc[-2]
        else:
            previous_fast_ema = None
            previous_slow_ema = None

        # Check for NaN values
        if pd.isna(current_fast_ema) or pd.isna(current_slow_ema):
            self.log_message("EMAs not ready (NaN values), skipping iteration")
            return

        # 4. Crossover Detection
        crossover_detected = self._detect_crossover(
            previous_fast_ema,
            previous_slow_ema,
            current_fast_ema,
            current_slow_ema
        )

        # 5. Position Check
        position = self.get_position(self.symbol)
        is_in_position = position is not None and position.quantity > 0

        # 6. Entry Logic - Bullish Crossover
        if crossover_detected == "bullish" and not is_in_position:
            self.log_message(
                f"BULLISH CROSSOVER DETECTED: Fast EMA ({current_fast_ema:.2f}) "
                f"crossed above Slow EMA ({current_slow_ema:.2f})"
            )
            self._execute_entry(current_price)

        # 7. Exit Logic - Bearish Crossover
        elif crossover_detected == "bearish" and is_in_position:
            self.log_message(
                f"BEARISH CROSSOVER DETECTED: Fast EMA ({current_fast_ema:.2f}) "
                f"crossed below Slow EMA ({current_slow_ema:.2f})"
            )
            self._execute_exit()

        # 8. Log current state
        position_status = "YES" if is_in_position else "NO"
        trend = "BULLISH" if current_fast_ema > current_slow_ema else "BEARISH"

        self.log_message(
            f"Price: ${current_price:.2f} | "
            f"Fast EMA (9): {current_fast_ema:.2f} | "
            f"Slow EMA (21): {current_slow_ema:.2f} | "
            f"Trend: {trend} | "
            f"Position: {position_status}"
        )

        # Update previous values for next iteration
        self.previous_fast_ema = current_fast_ema
        self.previous_slow_ema = current_slow_ema

    def _detect_crossover(self, prev_fast, prev_slow, curr_fast, curr_slow):
        """
        Detect if a crossover event has occurred.

        A crossover is detected by comparing the relationship between EMAs
        across two consecutive periods.

        Args:
            prev_fast: Previous fast EMA value
            prev_slow: Previous slow EMA value
            curr_fast: Current fast EMA value
            curr_slow: Current slow EMA value

        Returns:
            "bullish" if bullish crossover (fast crosses above slow)
            "bearish" if bearish crossover (fast crosses below slow)
            None if no crossover
        """
        # Need previous values to detect crossover
        if prev_fast is None or prev_slow is None:
            return None

        # Check for NaN values
        if pd.isna(prev_fast) or pd.isna(prev_slow):
            return None

        # Bullish Crossover: Fast EMA crosses ABOVE Slow EMA
        # Previous: fast <= slow
        # Current: fast > slow
        if prev_fast <= prev_slow and curr_fast > curr_slow:
            # Avoid repeated signals
            if self.last_crossover_type != "bullish":
                self.last_crossover_type = "bullish"
                return "bullish"

        # Bearish Crossover: Fast EMA crosses BELOW Slow EMA
        # Previous: fast >= slow
        # Current: fast < slow
        elif prev_fast >= prev_slow and curr_fast < curr_slow:
            # Avoid repeated signals
            if self.last_crossover_type != "bearish":
                self.last_crossover_type = "bearish"
                return "bearish"

        return None

    def _calculate_position_size(self, price):
        """
        Calculate appropriate position size using 100% of available cash.

        Args:
            price: Current price per share

        Returns:
            Integer quantity to trade
        """
        cash = self.get_cash()

        # Use specified cash allocation (default 100%)
        dollar_amount = cash * self.cash_allocation

        # Calculate quantity
        quantity = int(dollar_amount / price)

        # Ensure at least 1 share
        quantity = max(1, quantity)

        self.log_message(
            f"Position sizing: ${dollar_amount:.2f} / ${price:.2f} = {quantity} shares"
        )

        return quantity

    def _execute_entry(self, price):
        """
        Execute entry order (buy).

        Args:
            price: Current price for position sizing
        """
        quantity = self._calculate_position_size(price)

        # Create buy order
        order = self.create_order(
            self.symbol,
            quantity=quantity,
            side="buy"
        )

        # Submit order
        self.submit_order(order)

        # Update state
        self.entry_price = price
        self.entry_time = self.get_datetime()
        self.position_type = "long"

        self.log_message(
            f"ENTRY ORDER PLACED: BUY {quantity} shares of {self.symbol} "
            f"at ${price:.2f} (Total: ${quantity * price:.2f})"
        )

    def _execute_exit(self):
        """
        Execute exit order (sell all shares).
        """
        # Get current position
        position = self.get_position(self.symbol)

        if position is None or position.quantity <= 0:
            self.log_message("No position to exit")
            return

        # Close all positions for this symbol
        self.sell_all()

        # Calculate P&L
        exit_price = self.get_last_price(self.symbol)
        if self.entry_price and exit_price:
            pnl_pct = ((exit_price - self.entry_price) / self.entry_price) * 100
            pnl_dollars = (exit_price - self.entry_price) * position.quantity

            self.log_message(
                f"EXIT ORDER PLACED: SELL {position.quantity} shares of {self.symbol} "
                f"at ${exit_price:.2f} | "
                f"Entry: ${self.entry_price:.2f} | "
                f"P&L: {pnl_pct:+.2f}% (${pnl_dollars:+.2f})"
            )
        else:
            self.log_message(
                f"EXIT ORDER PLACED: SELL {position.quantity} shares of {self.symbol}"
            )

        # Reset state
        self.entry_price = None
        self.entry_time = None
        self.position_type = None


# Backtesting configuration (if running as main file)
if __name__ == "__main__":
    from lumibot.backtesting import YahooDataBacktesting
    from lumibot.entities import TradingFee

    # Backtest parameters
    backtesting_start = datetime(2022, 1, 1)
    backtesting_end = datetime(2023, 12, 31)

    # Trading fees (0.1% per trade)
    trading_fee = TradingFee(percent_fee=0.001)

    # Strategy parameters
    strategy_params = {
        "symbol": "SPY",
        "timeframe": "1D",
        "fast_ema_period": 9,
        "slow_ema_period": 21,
        "cash_allocation": 1.0,  # 100% of cash
    }

    print("=" * 70)
    print("EMA CROSSOVER STRATEGY BACKTEST")
    print("=" * 70)
    print(f"Symbol: {strategy_params['symbol']}")
    print(f"Fast EMA: {strategy_params['fast_ema_period']} days")
    print(f"Slow EMA: {strategy_params['slow_ema_period']} days")
    print(f"Period: {backtesting_start.date()} to {backtesting_end.date()}")
    print(f"Cash Allocation: {strategy_params['cash_allocation'] * 100}%")
    print("=" * 70)
    print()

    # Run backtest
    EMACrossoverStrategy.backtest(
        YahooDataBacktesting,
        backtesting_start,
        backtesting_end,
        parameters=strategy_params,
        buy_trading_fees=[trading_fee],
        sell_trading_fees=[trading_fee],
        benchmark_asset=strategy_params['symbol']
    )

    print()
    print("=" * 70)
    print("BACKTEST COMPLETE")
    print("=" * 70)
    print()
    print("To run this backtest, execute:")
    print("  python ema_crossover_test.py")
    print()
    print("To use in live trading or paper trading:")
    print("  from ema_crossover_test import EMACrossoverStrategy")
    print("  # Then instantiate with your broker configuration")
    print("=" * 70)
