"""
No-Loss Stock Investment Strategy - Lumibot Implementation

Generated by: Claude Code AI Agents (lumibot-coder)
Date: 2025-10-26
Strategy: Buy stock + protective put + call debit spread for zero downside risk

Components:
- Long stock (100 shares)
- Long protective put (married put) at-the-money
- Long call at-the-money + Short call out-of-the-money (call debit spread)

Net Effect:
- Downside protected by put (cannot lose principal)
- Upside limited to short call strike
- Net cost ≈ $0 (call spread offsets put premium)

WARNING: This is for educational purposes. Always paper trade before live trading.
"""

from lumibot.strategies import Strategy
from lumibot.entities import Asset
from lumibot.backtesting import PolygonDataBacktesting
from datetime import datetime, date, timedelta
from typing import Optional, Dict
import traceback


class NoLossStrategy(Strategy):
    """
    No-Loss Stock Investment Strategy

    This strategy creates a position with zero downside risk by combining:
    1. Long Stock Position
    2. Married Put (protective put at-the-money)
    3. Call Debit Spread (long ATM call + short OTM call)

    The call debit spread premium offsets the protective put cost,
    resulting in a net-zero or minimal cost position with full downside protection.
    """

    parameters = {
        "symbol": "SPY",                # Stock symbol to trade
        "shares_per_position": 100,     # Must be multiple of 100 for options alignment
        "dte_min": 30,                  # Minimum days to expiration
        "dte_max": 90,                  # Maximum days to expiration
        "put_strike_offset_pct": 0.0,   # Put strike % below stock (0.0 = ATM)
        "long_call_offset_pct": 0.0,    # Long call % above stock (0.0 = ATM)
        "short_call_offset_pct": 0.08,  # Short call % above stock (8% OTM)
        "max_net_debit": 100,           # Max acceptable net debit for entire position ($)
        "min_option_liquidity": 5,      # Minimum open interest required
        "check_frequency": "1D",        # How often to run strategy logic
    }

    def initialize(self):
        """
        Initialize strategy parameters and state variables.

        Sets trading frequency, loads parameters, and initializes
        state tracking for the no-loss position.
        """
        # Trading frequency and timing
        self.sleeptime = self.parameters.get("check_frequency", "1D")
        self.minutes_before_closing = 15  # Stop trading 15 min before market close

        # Strategy parameters
        self.symbol = self.parameters.get("symbol", "SPY")
        self.shares_per_position = self.parameters.get("shares_per_position", 100)
        self.dte_min = self.parameters.get("dte_min", 30)
        self.dte_max = self.parameters.get("dte_max", 90)
        self.put_strike_offset_pct = self.parameters.get("put_strike_offset_pct", 0.0)
        self.long_call_offset_pct = self.parameters.get("long_call_offset_pct", 0.0)
        self.short_call_offset_pct = self.parameters.get("short_call_offset_pct", 0.08)
        self.max_net_debit = self.parameters.get("max_net_debit", 100)
        self.min_option_liquidity = self.parameters.get("min_option_liquidity", 5)

        # Position state tracking
        self.position_entry_date = None
        self.position_expiration = None
        self.position_strikes = None  # Dict: {'put': X, 'long_call': Y, 'short_call': Z}
        self.position_entry_stock_price = None

        self.log_message("=" * 60)
        self.log_message("No-Loss Strategy Initialized")
        self.log_message(f"Symbol: {self.symbol}")
        self.log_message(f"Position Size: {self.shares_per_position} shares")
        self.log_message(f"DTE Range: {self.dte_min}-{self.dte_max} days")
        self.log_message(f"Max Net Debit: ${self.max_net_debit}")
        self.log_message("=" * 60)

    def on_trading_iteration(self):
        """
        Main trading logic executed at each iteration.

        Flow:
        1. Check if we already have an active no-loss position
        2. If no position: Evaluate entry opportunity
        3. If position exists: Monitor status and check expiration
        """
        try:
            current_date = self.get_datetime().date()
            self.log_message(f"\n[{current_date}] Starting trading iteration...")

            # Check if we have an active position
            has_position = self.has_active_no_loss_position()

            if not has_position:
                self.log_message("No active position detected.")
                self.attempt_entry()
            else:
                self.log_message("Active no-loss position detected.")
                self.monitor_position()

        except Exception as e:
            self.log_message(f"ERROR in on_trading_iteration: {str(e)}")
            self.log_message(f"Traceback: {traceback.format_exc()}")

    def has_active_no_loss_position(self) -> bool:
        """
        Check if we currently have an active no-loss position.

        A complete no-loss position requires:
        - Stock position (100+ shares)
        - Protective put option
        - Long call option
        - Short call option

        Returns:
            True if all components are present, False otherwise
        """
        try:
            # Check if we have recorded position state
            if not self.position_strikes or not self.position_expiration:
                return False

            # Check stock position
            stock_position = self.get_position(self.symbol)
            if not stock_position or stock_position.quantity < self.shares_per_position:
                self.log_message("Stock position missing or insufficient")
                return False

            # Check protective put
            put_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=self.position_expiration,
                strike=self.position_strikes['put'],
                right=Asset.OptionRight.PUT
            )
            put_position = self.get_position(put_asset)
            if not put_position or put_position.quantity < 1:
                self.log_message("Protective put position missing")
                return False

            # Check long call
            long_call_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=self.position_expiration,
                strike=self.position_strikes['long_call'],
                right=Asset.OptionRight.CALL
            )
            long_call_position = self.get_position(long_call_asset)
            if not long_call_position or long_call_position.quantity < 1:
                self.log_message("Long call position missing")
                return False

            # Check short call (should be negative quantity)
            short_call_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=self.position_expiration,
                strike=self.position_strikes['short_call'],
                right=Asset.OptionRight.CALL
            )
            short_call_position = self.get_position(short_call_asset)
            if not short_call_position or short_call_position.quantity >= 0:
                self.log_message("Short call position missing")
                return False

            # All components present
            return True

        except Exception as e:
            self.log_message(f"ERROR checking position: {str(e)}")
            return False

    def attempt_entry(self):
        """
        Attempt to enter a new no-loss position.

        Steps:
        1. Get current stock price
        2. Find suitable options expiration (30-90 DTE)
        3. Calculate optimal strikes for put and calls
        4. Verify net debit is acceptable
        5. Execute all 4 orders (stock + 3 options)
        6. Record position details
        """
        try:
            self.log_message("Evaluating entry opportunity...")

            # Step 1: Get current stock price
            current_price = self.get_last_price(self.symbol)
            if current_price is None or current_price <= 0:
                self.log_message(f"ERROR: Invalid stock price: {current_price}")
                return

            self.log_message(f"Current {self.symbol} price: ${current_price:.2f}")

            # Step 2: Find target expiration
            target_expiry = self.find_target_expiration()
            if not target_expiry:
                self.log_message("No suitable expiration found in target range")
                return

            dte = (target_expiry - self.get_datetime().date()).days
            self.log_message(f"Target expiration: {target_expiry} ({dte} DTE)")

            # Step 3: Calculate optimal strikes
            strikes = self.calculate_optimal_strikes(current_price, target_expiry)
            if not strikes:
                self.log_message("Could not calculate optimal strikes")
                return

            self.log_message(f"Strike prices:")
            self.log_message(f"  Put: ${strikes['put']:.2f}")
            self.log_message(f"  Long Call: ${strikes['long_call']:.2f}")
            self.log_message(f"  Short Call: ${strikes['short_call']:.2f}")

            # Step 4: Calculate net debit
            net_debit = self.calculate_net_debit(target_expiry, strikes, current_price)
            if net_debit is None or net_debit == float('inf'):
                self.log_message("Could not calculate net debit (missing prices)")
                return

            self.log_message(f"Calculated net debit: ${net_debit:.2f}")

            # Step 5: Verify acceptable debit
            if net_debit > self.max_net_debit:
                self.log_message(f"Net debit ${net_debit:.2f} exceeds max ${self.max_net_debit}")
                return

            # Step 6: Execute entry
            self.log_message("Net debit acceptable. Executing entry orders...")
            success = self.execute_no_loss_entry(target_expiry, strikes, current_price)

            if success:
                # Record position details
                self.position_entry_date = self.get_datetime().date()
                self.position_expiration = target_expiry
                self.position_strikes = strikes
                self.position_entry_stock_price = current_price

                self.log_message("=" * 60)
                self.log_message("[SUCCESS] No-loss position entered successfully!")
                self.log_message(f"Entry Date: {self.position_entry_date}")
                self.log_message(f"Stock Price: ${current_price:.2f}")
                self.log_message(f"Net Debit: ${net_debit:.2f}")
                self.log_message(f"Expiration: {target_expiry} ({dte} DTE)")
                self.log_message("=" * 60)
            else:
                self.log_message("[FAILED] Could not complete entry")

        except Exception as e:
            self.log_message(f"ERROR in attempt_entry: {str(e)}")
            self.log_message(f"Traceback: {traceback.format_exc()}")

    def find_target_expiration(self) -> Optional[date]:
        """
        Find an options expiration between dte_min and dte_max days out.

        Returns:
            date object for target expiration, or None if not found
        """
        try:
            # Get option chains
            chains_dict = self.get_chains(Asset(self.symbol))
            if not chains_dict or 'Chains' not in chains_dict:
                self.log_message("ERROR: No option chains available")
                return None

            chains = chains_dict['Chains']
            if 'PUT' not in chains:
                self.log_message("ERROR: No PUT options found")
                return None

            # Get all available expirations (keys are date strings)
            put_chains = chains['PUT']
            if not put_chains:
                self.log_message("ERROR: No expirations found")
                return None

            # Convert string dates to date objects
            from datetime import datetime as dt
            expiries = [dt.strptime(date_str, '%Y-%m-%d').date()
                       for date_str in put_chains.keys()]
            expiries = sorted(expiries)

            # Filter to target DTE range
            today = self.get_datetime().date()
            target_expiries = [
                exp for exp in expiries
                if self.dte_min <= (exp - today).days <= self.dte_max
            ]

            if not target_expiries:
                self.log_message(f"No expirations in range {self.dte_min}-{self.dte_max} DTE")
                return None

            # Return expiration closest to middle of range
            target_dte = (self.dte_min + self.dte_max) // 2
            best_expiry = min(target_expiries, key=lambda exp: abs((exp - today).days - target_dte))

            return best_expiry

        except Exception as e:
            self.log_message(f"ERROR in find_target_expiration: {str(e)}")
            return None

    def calculate_optimal_strikes(self, current_price: float, expiry: date) -> Optional[Dict[str, float]]:
        """
        Calculate optimal strike prices for the three options.

        Args:
            current_price: Current stock price
            expiry: Target expiration date

        Returns:
            Dictionary with keys 'put', 'long_call', 'short_call', or None if error
        """
        try:
            # Get option chains
            chains_dict = self.get_chains(Asset(self.symbol))
            if not chains_dict or 'Chains' not in chains_dict:
                return None

            chains = chains_dict['Chains']

            # Get available strikes from PUT chain for this expiry
            expiry_str = expiry.strftime('%Y-%m-%d')
            if 'PUT' not in chains or expiry_str not in chains['PUT']:
                self.log_message(f"ERROR: No PUT options for {expiry_str}")
                return None

            # Get all strikes for this expiration
            put_options = chains['PUT'][expiry_str]
            strikes_available = sorted([float(strike) for strike in put_options.keys()])

            if not strikes_available:
                self.log_message("ERROR: No strikes available")
                return None

            # Calculate target strikes
            put_target = current_price * (1 - self.put_strike_offset_pct)
            long_call_target = current_price * (1 + self.long_call_offset_pct)
            short_call_target = current_price * (1 + self.short_call_offset_pct)

            # Find closest available strikes
            put_strike = min(strikes_available, key=lambda s: abs(s - put_target))
            long_call_strike = min(strikes_available, key=lambda s: abs(s - long_call_target))
            short_call_strike = min(strikes_available, key=lambda s: abs(s - short_call_target))

            # Validate: short call should be higher than long call
            if short_call_strike <= long_call_strike:
                self.log_message("ERROR: Short call strike must be higher than long call")
                return None

            return {
                'put': put_strike,
                'long_call': long_call_strike,
                'short_call': short_call_strike
            }

        except Exception as e:
            self.log_message(f"ERROR in calculate_optimal_strikes: {str(e)}")
            return None

    def calculate_net_debit(self, expiry: date, strikes: Dict[str, float], stock_price: float) -> Optional[float]:
        """
        Calculate total net debit for the entire position.

        Net Debit = Stock Cost + Put Premium + Long Call Premium - Short Call Premium

        Args:
            expiry: Expiration date
            strikes: Dictionary with put, long_call, short_call strikes
            stock_price: Current stock price

        Returns:
            Net debit in dollars, or None if prices unavailable
        """
        try:
            # Stock cost (for 100 shares)
            stock_cost = stock_price * self.shares_per_position

            # Get put price
            put_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=expiry,
                strike=strikes['put'],
                right=Asset.OptionRight.PUT
            )
            put_price = self.get_last_price(put_asset)
            if put_price is None:
                self.log_message("ERROR: Could not get put price")
                return None
            put_cost = put_price * 100  # Options are per 100 shares

            # Get long call price
            long_call_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=expiry,
                strike=strikes['long_call'],
                right=Asset.OptionRight.CALL
            )
            long_call_price = self.get_last_price(long_call_asset)
            if long_call_price is None:
                self.log_message("ERROR: Could not get long call price")
                return None
            long_call_cost = long_call_price * 100

            # Get short call price (this is a credit)
            short_call_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=expiry,
                strike=strikes['short_call'],
                right=Asset.OptionRight.CALL
            )
            short_call_price = self.get_last_price(short_call_asset)
            if short_call_price is None:
                self.log_message("ERROR: Could not get short call price")
                return None
            short_call_credit = short_call_price * 100

            # Calculate net debit
            net_debit = stock_cost + put_cost + long_call_cost - short_call_credit

            # Log breakdown
            self.log_message(f"Cost breakdown:")
            self.log_message(f"  Stock ({self.shares_per_position} shares @ ${stock_price:.2f}): ${stock_cost:.2f}")
            self.log_message(f"  Put Premium: ${put_cost:.2f}")
            self.log_message(f"  Long Call Premium: ${long_call_cost:.2f}")
            self.log_message(f"  Short Call Credit: -${short_call_credit:.2f}")
            self.log_message(f"  NET DEBIT: ${net_debit:.2f}")

            return net_debit

        except Exception as e:
            self.log_message(f"ERROR in calculate_net_debit: {str(e)}")
            return None

    def execute_no_loss_entry(self, expiry: date, strikes: Dict[str, float], stock_price: float) -> bool:
        """
        Execute all 4 orders to enter the no-loss position.

        Order of execution:
        1. Buy stock
        2. Buy protective put
        3. Buy long call
        4. Sell short call

        Args:
            expiry: Expiration date for options
            strikes: Dictionary with strike prices
            stock_price: Current stock price

        Returns:
            True if all orders successfully submitted, False otherwise
        """
        try:
            # Order 1: Buy stock
            self.log_message(f"[1/4] Buying {self.shares_per_position} shares of {self.symbol}...")
            stock_order = self.create_order(self.symbol, self.shares_per_position, "buy")
            self.submit_order(stock_order)
            self.log_message(f"  Stock order submitted: {self.shares_per_position} shares @ ~${stock_price:.2f}")

            # Order 2: Buy protective put
            self.log_message(f"[2/4] Buying protective put (strike ${strikes['put']:.2f})...")
            put_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=expiry,
                strike=strikes['put'],
                right=Asset.OptionRight.PUT
            )
            put_order = self.create_order(put_asset, 1, "buy")
            self.submit_order(put_order)
            self.log_message(f"  Put order submitted: 1 contract")

            # Order 3: Buy long call
            self.log_message(f"[3/4] Buying long call (strike ${strikes['long_call']:.2f})...")
            long_call_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=expiry,
                strike=strikes['long_call'],
                right=Asset.OptionRight.CALL
            )
            long_call_order = self.create_order(long_call_asset, 1, "buy")
            self.submit_order(long_call_order)
            self.log_message(f"  Long call order submitted: 1 contract")

            # Order 4: Sell short call
            self.log_message(f"[4/4] Selling short call (strike ${strikes['short_call']:.2f})...")
            short_call_asset = Asset(
                symbol=self.symbol,
                asset_type=Asset.AssetType.OPTION,
                expiration=expiry,
                strike=strikes['short_call'],
                right=Asset.OptionRight.CALL
            )
            short_call_order = self.create_order(short_call_asset, 1, "sell")
            self.submit_order(short_call_order)
            self.log_message(f"  Short call order submitted: 1 contract")

            self.log_message("All 4 orders submitted successfully")
            return True

        except Exception as e:
            self.log_message(f"ERROR during order execution: {str(e)}")
            self.log_message(f"Traceback: {traceback.format_exc()}")
            return False

    def monitor_position(self):
        """
        Monitor existing no-loss position and log status.

        Checks:
        - Days to expiration
        - Current stock price vs strikes
        - Potential profit/loss
        - Whether approaching expiration
        """
        try:
            if not self.position_expiration or not self.position_strikes:
                return

            # Calculate days to expiration
            current_date = self.get_datetime().date()
            dte = (self.position_expiration - current_date).days

            # Get current stock price
            current_price = self.get_last_price(self.symbol)
            if current_price is None:
                self.log_message("ERROR: Could not get current price")
                return

            # Calculate price change
            price_change = current_price - self.position_entry_stock_price
            price_change_pct = (price_change / self.position_entry_stock_price) * 100

            # Log status
            self.log_message("-" * 60)
            self.log_message("Position Status:")
            self.log_message(f"  Days to Expiration: {dte}")
            self.log_message(f"  Entry Price: ${self.position_entry_stock_price:.2f}")
            self.log_message(f"  Current Price: ${current_price:.2f}")
            self.log_message(f"  Change: ${price_change:+.2f} ({price_change_pct:+.2f}%)")
            self.log_message(f"  Put Strike (floor): ${self.position_strikes['put']:.2f}")
            self.log_message(f"  Short Call Strike (ceiling): ${self.position_strikes['short_call']:.2f}")

            # Determine position status
            if current_price < self.position_strikes['put']:
                self.log_message(f"  STATUS: Below put strike (protected)")
            elif current_price > self.position_strikes['short_call']:
                self.log_message(f"  STATUS: Above short call (max profit)")
            else:
                self.log_message(f"  STATUS: Within profit zone")

            # Check if approaching expiration
            if dte <= 7:
                self.log_message(f"  WARNING: Expiring in {dte} days!")
                self.log_message(f"  Consider closing or rolling position")

            self.log_message("-" * 60)

        except Exception as e:
            self.log_message(f"ERROR in monitor_position: {str(e)}")

    def before_market_closes(self):
        """
        Execute actions before market close.

        Checks if options are expiring today and logs warning.
        """
        try:
            if self.position_expiration:
                current_date = self.get_datetime().date()
                dte = (self.position_expiration - current_date).days

                if dte == 0:
                    self.log_message("=" * 60)
                    self.log_message("WARNING: OPTIONS EXPIRING TODAY!")
                    self.log_message("Position will be automatically closed or assigned")
                    self.log_message("=" * 60)

        except Exception as e:
            self.log_message(f"ERROR in before_market_closes: {str(e)}")


# Backtest configuration
if __name__ == "__main__":
    # Add project root to path for credentials import
    import sys
    from pathlib import Path
    project_root = Path(__file__).parent.parent.parent.parent
    sys.path.insert(0, str(project_root))

    # Import credentials
    try:
        from credentials import POLYGON_CONFIG, IS_BACKTESTING
    except ImportError as e:
        print("ERROR: Could not import credentials.py")
        print(f"Details: {e}")
        print(f"Looking in: {project_root}")
        print("Please create credentials.py with POLYGON_CONFIG")
        exit(1)

    # Backtest parameters
    # Short test period for quick validation
    backtesting_start = datetime(2024, 1, 1)
    backtesting_end = datetime(2024, 1, 31)  # Just January for quick testing

    print("=" * 70)
    print("No-Loss Strategy Backtest")
    print("=" * 70)
    print(f"Period: {backtesting_start.date()} to {backtesting_end.date()}")
    print(f"Symbol: SPY")
    print(f"Data Source: Polygon.io (Options + Stock)")
    print("=" * 70)

    # Run backtest
    NoLossStrategy.backtest(
        PolygonDataBacktesting,
        backtesting_start,
        backtesting_end,
        parameters={
            "symbol": "SPY",
            "shares_per_position": 100,
            "dte_min": 30,
            "dte_max": 90,
            "short_call_offset_pct": 0.08,  # 8% OTM short call
            "max_net_debit": 100,
        },
        polygon_api_key=POLYGON_CONFIG["API_KEY"],
        polygon_has_paid_subscription=True,  # Required for options data
        benchmark_asset="SPY",
        show_plot=True,
        show_tearsheet=True,
        save_tearsheet=True,
        tearsheet_file="no_loss_strategy_tearsheet.html"
    )

    print("\nBacktest complete! Check no_loss_strategy_tearsheet.html for results.")
